CREATE TABLE EESTACIONES_JSON(
    TIPO_ESTACION TEXT,
    PROVINCIA TEXT,
    MUNICIPIO TEXT,
    CODIGO_POSTAL INT,
    DIRECCION TEXT,
    NUMERO_ESTACION INT,
    HORARIO TEXT,
    CORREO TEXT
)

CREATE TABLE EESTACIONES_XML(
    ESTACION TEXT,
    DENOMINACION TEXT,
    OPERADOR TEXT,
    DIRECCION TEXT,
    CODIGO_POSTAL INT,
    MUNICIPIO TEXT,
    CODIGO_MUNICIPIO INT,
    LATITUD INT,
    LOGITUD INT,
    COLUMNA_GEOCODIFICADA TEXT,
    LOCALIZADOR_GOOGLE_MAPS TEXT,
    SERVICIOS_TERRITORIALES TEXT,
    HORARIO_SERVICIO TEXT,
    EMAIL TEXT,
    WEB TEXT
)

CREATE TABLE EESTACIONES_CSV(
    ESTACION TEXT,
    ENDEREZO TEXT,
    CONCELLO TEXT,
    CODIGO_POSTAL TEXT,
    PROVINCIA TEXT,
    TELEFONO TEXT,
    HORARIO TEXT,
    SOLICITUD_CITA_PREVIA TEXT,
    EMAIL TEXT,
    COORDENADAS_GGOGLE_MAPS TEXT,
    LATITUD TEXT,
    LONGITUD TEXT
)